# Generated by Django 6.1 on 2026-09-01 23:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0003_semestre_date_debut_semestre_date_fin'),
        ('students', '0003_remove_student_classe_student_niveau'),
        ('subjects', '0002_subject_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evaluation', models.CharField(choices=[('cc1', 'Contrôle continu 1'), ('cc2', 'Contrôle continu 2'), ('devoir', 'Devoir'), ('examen', 'Examen final')], max_length=20)),
                ('session', models.PositiveSmallIntegerField(choices=[(1, 'Session 1'), (2, 'Session 2')], default=1)),
                ('date', models.DateField()),
                ('annee_universitaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='academic.anneeuniversitaire')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.evaluation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
            ],
        ),
    ]
