# Generated by Django 6.1 on 2026-09-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
