# Generated by Django 6.1 on 2026-09-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='raw_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='identifiant',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
