# Generated by Django 6.1 on 2026-09-01 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence', models.DateField()),
                ('justifiee', models.BooleanField(default=False)),
                ('justification', models.TextField(blank=True, null=True)),
                ('date_justification', models.DateField(blank=True, null=True)),
                ('rattrapage_effectue', models.BooleanField(default=False)),
                ('note_rattrapage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('date_rattrapage', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
