# Generated by Django 6.1 on 2026-09-01 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absences', '0001_initial'),
        ('grades', '0001_initial'),
        ('students', '0003_remove_student_classe_student_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='grades.evaluation'),
        ),
        migrations.AddField(
            model_name='absence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='students.student'),
        ),
    ]
