# Generated by Django 6.1 on 2026-09-04 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0003_remove_absence_evaluation_absence_type_evaluation'),
        ('subjects', '0003_subject_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='subjects.subject'),
        ),
    ]
