# Generated by Django 6.1.1 on 2026-09-09 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0005_remove_absence_type_evaluation'),
        ('students', '0005_student_raw_password'),
        ('subjects', '0003_subject_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='subjects.subject'),
        ),
        migrations.AddConstraint(
            model_name='absence',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'date_absence'), name='unique_student_subject_absence_date'),
        ),
    ]
