# Generated by Django 6.1 on 2026-09-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niveau',
            name='filiere',
        ),
        migrations.AddField(
            model_name='niveau',
            name='filieres',
            field=models.ManyToManyField(related_name='niveaux', to='academic.filiere'),
        ),
    ]
