# Generated by Django 6.1 on 2026-09-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_remove_niveau_filiere_niveau_filieres'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semestre',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
