# Generated by Django 6.1 on 2026-09-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_semestre_date_debut_semestre_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='code',
            field=models.CharField(blank=True, choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=2, null=True, unique=True),
        ),
    ]
