# Generated by Django 6.1 on 2026-09-02 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_niveau_code'),
        ('students', '0003_remove_student_classe_student_niveau'),
        ('subjects', '0003_subject_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_obtenus', models.PositiveIntegerField()),
                ('credits_maximum', models.PositiveIntegerField(default=60)),
                ('passage_avec_arrieres', models.BooleanField(default=False)),
                ('date_passage', models.DateField(auto_now_add=True)),
                ('ancien_niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progressions_depart', to='academic.niveau')),
                ('annee_universitaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progressions', to='academic.anneeuniversitaire')),
                ('nouveau_niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progressions_arrivee', to='academic.niveau')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Arriere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('non_valide', 'Non validé'), ('valide', 'Validé')], default='non_valide', max_length=20)),
                ('date_validation', models.DateField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrieres', to='subjects.subject')),
                ('progression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrieres', to='academic.progression')),
            ],
        ),
    ]
