# Generated by Django 6.1 on 2026-09-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_progression_arriere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='nom',
            field=models.CharField(choices=[('S1', 'Semestre 1 (L1)'), ('S2', 'Semestre 2 (L1)'), ('S3', 'Semestre 3 (L2)'), ('S4', 'Semestre 4 (L2)'), ('S5', 'Semestre 5 (L3)'), ('S6', 'Semestre 6 (L3)'), ('S7', 'Semestre 7 (M1)'), ('S8', 'Semestre 8 (M1)'), ('S9', 'Semestre 9 (M2)'), ('S10', 'Semestre 10 (M2)')], max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='semestre',
            unique_together={('niveau', 'nom')},
        ),
    ]
