# Generated by Django 6.1 on 2026-09-02 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_alter_semestre_nom_alter_semestre_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semestre',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='semestre',
            name='annee_universitaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='academic.anneeuniversitaire'),
        ),
        migrations.AlterUniqueTogether(
            name='semestre',
            unique_together={('niveau', 'annee_universitaire', 'nom')},
        ),
    ]
