# Generated by Django 6.1 on 2026-09-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_semestre_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneeuniversitaire',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anneeuniversitaire',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
