# Generated by Django 6.1 on 2026-09-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0002_teacher_prenom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('teachers', models.ManyToManyField(blank=True, related_name='subjects', to='teachers.teacher')),
            ],
        ),
    ]
