# Generated by Django 6.1 on 2026-09-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
