# Generated by Django 6.1.1 on 2026-09-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_alter_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
    ]
