# Generated by Django 6.1.1 on 2026-09-09 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_anneeuniversitaire_date_debut_and_more'),
        ('subjects', '0006_remove_subject_code'),
        ('teachers', '0003_teacher_raw_password_alter_teacher_identifiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enseignements', to='academic.filiere')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enseignements', to='academic.semestre')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='teachers.teacher')),
            ],
            options={
                'ordering': ['subject__nom', 'semestre__niveau__code', 'filiere__code', 'teacher__nom'],
                'constraints': [models.UniqueConstraint(fields=('subject', 'teacher', 'semestre', 'filiere'), name='unique_subject_teacher_semestre_filiere')],
            },
        ),
    ]
