# Generated by Django 6.1 on 2026-09-01 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classe',
        ),
        migrations.AddField(
            model_name='student',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.niveau'),
        ),
    ]
