# Generated by Django 6.1 on 2026-09-04 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_anneeuniversitaire_date_debut_and_more'),
        ('students', '0003_remove_student_classe_student_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.filiere'),
        ),
    ]
