# Generated by Django 6.1 on 2026-09-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='raw_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
